
package com.phuong.entities;
// Generated Nov 8, 2017 10:29:07 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * PhuongPersonalProjectRole generated by hbm2java
 */
@Entity
@Table(name = "phuong_personal_project_role", catalog = "fresher")
public class PhuongPersonalProjectRole implements java.io.Serializable {

	private PhuongPersonalProjectRoleId id;
	private PhuongPersonal phuongPersonal;
	private PhuongProjectRole phuongProjectRole;
	private String projectName;
	private Date startDate;
	private Date endDate;

	public PhuongPersonalProjectRole() {
	}

	public PhuongPersonalProjectRole(PhuongPersonalProjectRoleId id, PhuongPersonal phuongPersonal,
			PhuongProjectRole phuongProjectRole) {
		this.id = id;
		this.phuongPersonal = phuongPersonal;
		this.phuongProjectRole = phuongProjectRole;
	}

	public PhuongPersonalProjectRole(PhuongPersonalProjectRoleId id, PhuongPersonal phuongPersonal,
			PhuongProjectRole phuongProjectRole, String projectName, Date startDate, Date endDate) {
		this.id = id;
		this.phuongPersonal = phuongPersonal;
		this.phuongProjectRole = phuongProjectRole;
		this.projectName = projectName;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idPersonal", column = @Column(name = "id_personal", nullable = false)),
			@AttributeOverride(name = "idProjectRole", column = @Column(name = "id_project_role", nullable = false)) })
	public PhuongPersonalProjectRoleId getId() {
		return this.id;
	}

	public void setId(PhuongPersonalProjectRoleId id) {
		this.id = id;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_personal", nullable = false, insertable = false, updatable = false)
	public PhuongPersonal getPhuongPersonal() {
		return this.phuongPersonal;
	}

	public void setPhuongPersonal(PhuongPersonal phuongPersonal) {
		this.phuongPersonal = phuongPersonal;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_project_role", nullable = false, insertable = false, updatable = false)
	public PhuongProjectRole getPhuongProjectRole() {
		return this.phuongProjectRole;
	}

	public void setPhuongProjectRole(PhuongProjectRole phuongProjectRole) {
		this.phuongProjectRole = phuongProjectRole;
	}

	@Column(name = "project_name", length = 100)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
