package com.phuong.entities;
// Generated Nov 8, 2017 10:29:07 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * PhuongPersonal generated by hbm2java
 */
@Entity
@Table(name = "phuong_personal", catalog = "fresher")
public class PhuongPersonal implements java.io.Serializable {

	private Integer id;
	private String phone;
	private String name;
	private Date dob;
	private Byte sex;
	private String skill;
	private String note;
	private Set<PhuongPersonalProjectRole> phuongPersonalProjectRoles = new HashSet<PhuongPersonalProjectRole>(0);

	public PhuongPersonal() {
	}

	public PhuongPersonal(String phone, String name, Date dob, Byte sex, String skill, String note,
			Set<PhuongPersonalProjectRole> phuongPersonalProjectRoles) {
		this.phone = phone;
		this.name = name;
		this.dob = dob;
		this.sex = sex;
		this.skill = skill;
		this.note = note;
		this.phuongPersonalProjectRoles = phuongPersonalProjectRoles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "phone")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dob", length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "sex")
	public Byte getSex() {
		return this.sex;
	}

	public void setSex(Byte sex) {
		this.sex = sex;
	}

	@Column(name = "skill", length = 100)
	public String getSkill() {
		return this.skill;
	}

	public void setSkill(String skill) {
		this.skill = skill;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phuongPersonal")
	public Set<PhuongPersonalProjectRole> getPhuongPersonalProjectRoles() {
		return this.phuongPersonalProjectRoles;
	}

	public void setPhuongPersonalProjectRoles(Set<PhuongPersonalProjectRole> phuongPersonalProjectRoles) {
		this.phuongPersonalProjectRoles = phuongPersonalProjectRoles;
	}

}
