package com.phuong.entities;
// Generated Nov 8, 2017 10:29:07 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * PhuongProjectRole generated by hbm2java
 */
@Entity
@Table(name = "phuong_project_role", catalog = "fresher")
public class PhuongProjectRole implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Set<PhuongPersonalProjectRole> phuongPersonalProjectRoles = new HashSet<PhuongPersonalProjectRole>(0);

	public PhuongProjectRole() {
	}

	public PhuongProjectRole(String name, String description,
			Set<PhuongPersonalProjectRole> phuongPersonalProjectRoles) {
		this.name = name;
		this.description = description;
		this.phuongPersonalProjectRoles = phuongPersonalProjectRoles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phuongProjectRole")
	public Set<PhuongPersonalProjectRole> getPhuongPersonalProjectRoles() {
		return this.phuongPersonalProjectRoles;
	}

	public void setPhuongPersonalProjectRoles(Set<PhuongPersonalProjectRole> phuongPersonalProjectRoles) {
		this.phuongPersonalProjectRoles = phuongPersonalProjectRoles;
	}

}
